{{- range $.Values.provider.packages }}
{{ if ne . "" }}
apiVersion: pkg.ibm.crossplane.io/v1
kind: Provider
metadata:
  name: {{ regexReplaceAll "(:|@).*" . "" | trim | replace "/" "-" }}
spec:
  package: {{ . | trim }}
---
{{ end }}
{{- end }}
