---
apiVersion: apiextensions.ibm.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositekubernetesclusters.common.crossplane.io
spec:
  group: common.crossplane.io
  names:
    categories:
      - crossplane
    kind: CompositeKubernetesCluster
    plural: compositekubernetesclusters
  claimNames:
    categories:
      - crossplane
    kind: KubernetesCluster
    plural: kubernetesclusters
  connectionSecretKeys:
    - kubeconfig
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              version:
                description: Version specifies the desired Kubernetes version,
                  e.g. 1.15.
                type: string
            required:
              - version
