---
apiVersion: apiextensions.ibm.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositemachineinstances.common.crossplane.io
spec:
  group: common.crossplane.io
  names:
    categories:
      - crossplane
    kind: CompositeMachineInstance
    plural: compositemachineinstances
  claimNames:
    categories:
      - crossplane
    kind: MachineInstance
    plural: machineinstances
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
