apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: getting-started-with-aws-with-vpc
  annotations:
    guide: quickstart
    provider: aws
    vpc: new
spec:
  crossplane:
    version: ">=v1.0.0-0"
  dependsOn:
    # TODO(negz): Update Composition for compatibility with v0.17.0.
    - provider: crossplane/provider-aws
      version: "v0.16.0"
